FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block zookeeper_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='zookeeper') }}


{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set zookeeper_packages = [
            'java-1.8.0-openjdk'
            'zookeeper',
        ] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set zookeeper_packages = [
            'zookeeper',
        ] %}
    {% endif %}

{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set horizon_packages = [
                'java-1.8.0-openjdk',
                'zookeeper'
        ] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set zookeeper_packages = [
            'zookeeper',
        ] %}
{% endif %}

RUN curl -Lo zookeeper.tar.gz 'https://github.com/apache/zookeeper/archive/release-3.4.11.tar.gz'
RUN tar -xzf zookeeper.tar.gz -C /opt/zookeeper

{% endif %}

{{ macros.install_packages(zookeeper_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block zookeeper_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER zookeeper
